//Each new term in the Fibonacci sequence is generated by adding the previous
//two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
//8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
//whose values do not exceed four million, find the sum of the even-valued
//terms.

function SumOfEvenFib(){
    var seq = [1,2];
    var add = 0;

    while (true){
        var add = seq[seq.length-1]+seq[seq.length-2];
        if (add >= 4000000){
            break;
        };
        seq.push(add);
    }

    var sumEven = 0;
    for (var i = 0; i < seq.length;i++){
        if (seq[i]%2===0) {
            sumEven += seq[i]
        }
    }

    return sumEven;
}
